services:
  dev:
    image: lunarzdev/epsilon-dev-linux
    pull_policy: missing
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USERNAME: epsilon
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    container_name: epsilon_dev
    privileged: true
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      ROS_LOCALHOST_ONLY: "1"
      ROS_DOMAIN_ID: "42"
      ROS_WS: "/home/epsilon/epsilon_ws"
      DISPLAY: ${DISPLAY}
    volumes:
      - ${PWD}:/home/epsilon/epsilon_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /dev/dri:/dev/dri:cached
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /home/epsilon/epsilon_ws
